# Generated by Django 5.2.17 on 2026-08-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'permissions': [('add_image_document', 'Can add image documents'), ('change_image_document', 'Can change image documents')]},
        ),
    ]
